# -*- coding: utf-8 -*-
"""pdf test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6mmf08l5uaVGn8nD-E3LakqZlqW9tLC
"""

# 安裝 LangChain、PDF 解析工具與基礎向量庫
!pip install pdfplumber langchain langchain-community sentence-transformers faiss-cpu

import pdfplumber
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

def load_esg_pdf(file_path, company_name):
    all_chunks = []

    print(f"開始解析 PDF: {file_path}")

    # 1. 讀取 PDF 並保留頁碼
    with pdfplumber.open(file_path) as pdf:
        for i, page in enumerate(pdf.pages):
            text = page.extract_text()
            if text:
                # 建立 Document 物件，將頁碼存入 metadata
                doc = Document(
                    page_content=text,
                    metadata={
                        "company": company_name,
                        "page": i + 1,  # 頁碼從 1 開始計算
                        "source": f"{company_name}_ESG_Report"
                    }
                )
                all_chunks.append(doc)

    # 2. 文本切塊：將長頁面拆成小塊，便於後續 AI 偵測漂綠特徵 [cite: 37, 39]
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=600,
        chunk_overlap=60,
        separators=["\n\n", "\n", "。", "！", "？"]
    )

    split_docs = text_splitter.split_documents(all_chunks)
    print(f"✅ 處理完成！共生成 {len(split_docs)} 個文本區塊。")
    return split_docs

# 請將 "your_file.pdf" 換成你上傳的檔名
# "TSMC" 換成你想測試的公司名稱
docs = load_esg_pdf("test01.pdf", "緯創")

# 檢視第一個切塊的內容與頁碼標記
if len(docs) > 0:
    print(f"\n--- 範例區塊內容 (來自第 {docs[0].metadata['page']} 頁) ---")
    print(docs[0].page_content[:200])

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# 初始化 Embedding 模型 (建議用多國語言版本)
embeddings = HuggingFaceEmbeddings(model_name="paraphrase-multilingual-MiniLM-L12-v2")

# 建立並儲存向量庫
print("正在建立向量索引，請稍候...")
vector_db = FAISS.from_documents(docs, embeddings)
vector_db.save_local("wistron_faiss_index")
print("✅ 向量庫已建立並儲存！")

# 測試檢索：看看能不能抓到「水資源」相關的潛在漂綠風險
query = "水資源使用與回收數據"
search_results = vector_db.similarity_search(query, k=3)
for i, res in enumerate(search_results):
    print(f"\n結果 {i+1} (第 {res.metadata['page']} 頁):")
    print(res.page_content[:200])

# 安裝 Google 生成式 AI 套件
!pip install -q -U google-generativeai

import google.generativeai as genai
import json

# 1. 填入你的 API KEY
API_KEY = "AIzaSyBytAmATZTFdpSMAJbS-aglKfJdUwRdWOk"
genai.configure(api_key=API_KEY)

# 2. 根據你的「ESG資料.docx」設定最強分析師指令
SYSTEM_INSTRUCTION = """
# Role
你是一位頂尖的永續金融分析師、法政語言學家與 NLP 專家 [cite: 17]。你的專長是利用學術界最嚴謹的文本分析框架，偵測 ESG 報告書中的「漂綠行為」 [cite: 17]。

# Task
請針對提供的文本段落，嚴格套用以下【六大學術評估框架】進行深度掃描 [cite: 19]。你的目標是揪出文本中的「言行脫節（Decoupling）」現象、量化其漂綠風險 [cite: 19]。

# Evaluation Criteria (進階評估標準) [cite: 20, 21]
1. 軟性露與硬性揭露落差 (Soft vs. Hard Disclosure): 區分是實質行動（量化數據、KPI、第三方認證）還是象徵表態（空泛願景、口號） [cite: 22, 23, 25, 26]。
2. 選擇性揭與櫻桃挑選 (Selective Disclosure): 是否刻意挑選表現良好的小作為（如淨灘），卻隱瞞核心本業的巨大衝擊 [cite: 28, 29, 32]。
3. 文本可讀性與混淆視聽 (Readability & Obfuscation): 是否利用冗長句型、術語濫用或模糊詞彙掩蓋負面資訊 [cite: 34, 35, 37, 39]。
4. 表達性操弄與異常語氣 (Tone Management): 偵測異常正向情緒、讚美詞彙，或逃避責任的語氣 [cite: 40, 41, 43, 44]。
5. 缺乏實證與不可靠聲稱 (Unsubstantiated Claims): 是否缺乏數據來源、SGS 確信、會計師簽證或引用假標籤 [cite: 45, 46, 48, 49]。

# Output Format (JSON Only)
請嚴格以 JSON 格式輸出，不得有額外解釋：
{
  "overall_risk_level": "極高 / 高 / 中 / 低",
  "overall_risk_score": 0-100,
  "scoring": {
    "soft_vs_hard": 0-10,
    "selective_disclosure": 0-10,
    "readability": 0-10,
    "tone_management": 0-10,
    "unsubstantiated": 0-10
  },
  "evidence_summary": [
    { "quote": "原文句子", "page": "頁碼", "dimension": "維度名稱", "analysis": "深度診斷為何符合漂綠特徵" }
  ],
  "red_flags": ["給投資人的警示點 1", "關鍵盲區 2"]
}
"""

# 3. 初始化模型
model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    system_instruction=SYSTEM_INSTRUCTION,
    generation_config={"response_mime_type": "application/json"} # 強制輸出 JSON
)

def run_greenwashing_detector(search_docs):
    # 將檢索到的多個片段組合成一段分析文本
    combined_text = "\n\n".join([f"[Page {d.metadata['page']}]: {d.page_content}" for d in search_docs])

    print("AI 正在深度掃描文本中的漂綠風險...")
    response = model.generate_content(f"請分析以下緯創 ESG 報告書節錄內容：\n\n{combined_text}")

    # 解析 JSON
    analysis_result = json.loads(response.text)
    return analysis_result

# 測試：分析剛才搜尋出的片段
if 'search_results' in locals():
    final_json = run_greenwashing_detector(search_results)

    # 印出結果 (這就是未來要餵給 Streamlit 儀表板的數據)
    print(json.dumps(final_json, indent=2, ensure_ascii=False))

import google.generativeai as genai

# Assuming API_KEY is already defined from cell 2gFp5dX1xQpD
genai.configure(api_key=API_KEY)

print("--- 可用模型列表 ---")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)